site:
  title: Offline Diameter Docs
  start_page: quarkus-jdiameter::index.adoc

output:
  clean: true
  dir: target/site

content:
  sources:
    - url: .. # common module containing just the main index
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://github.com/eddiecarpenter/antora-ui-go-docs/releases/latest/download/ui-bundle.zip
    snapshot: true

runtime:
  fetch: false
  cache_dir: ./cache

asciidoc:
  attributes:
    kroki-fetch-diagram: true
    page-pagination: ''
    experimental: ''
    safe: 0

  extensions:
    - asciidoctor-kroki
